### ISSUE TITLE
Unable to use other pretrained weights

### ISSUE THREAD

**Issue by ansariyusuf** [megvii-model/HINet#8]
Hi,

Thank you for this wonderful project. I am able to successfully run the demo with the GOPRO weights on multiple images and it works flawlessly. However, if I just tweak the demo.yml file and change the pre-trained weights to HINet-SIDD-1x.pth, I get an error with the state_dit. I am new to PyTorch, so this may be a trivial issue. Your help and guidance are much appreciated. I am attaching the demo.yml file to this post and the output:
```

# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: demo
model_type: ImageRestorationModel
scale: 1
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 10

# single image inference and save image
img_path:
  input_img: ./demo/GOPR0384_11_00-000001.png
  output_img: ./demo/demo1.png

# network structures
network_g:
  type: HINet
  wf: 64
  hin_position_left: 3
  hin_position_right: 4

# path
path:
  pretrain_network_g: ./experiments/pretrained_models/HINet-SIDD-1x.pth
  strict_load_g: true
  resume_state: ~

# validation settings
val:
  grids: true
  crop_size: 256

# dist training settings
dist_params:
  backend: nccl
  port: 29500
```

The error log is as follows:
```
(HINet) C:\Users\Yusuf\Desktop\HMC Research\HINet>python basicsr/demo.py -opt options/demo/demo.yml
Disable distributed.
 load net keys <built-in method keys of collections.OrderedDict object at 0x000002284651FEA0>
Current net - loaded net:
Loaded net - current net:
  down_path_1.0.norm.bias
  down_path_1.0.norm.weight
  down_path_1.1.norm.bias
  down_path_1.1.norm.weight
  down_path_1.2.norm.bias
  down_path_1.2.norm.weight
  down_path_2.0.norm.bias
  down_path_2.0.norm.weight
  down_path_2.1.norm.bias
  down_path_2.1.norm.weight
  down_path_2.2.norm.bias
  down_path_2.2.norm.weight
Traceback (most recent call last):
  File "basicsr/demo.py", line 46, in <module>
    main()
  File "basicsr/demo.py", line 40, in main
    model = create_model(opt)
  File "c:\users\yusuf\desktop\hmc research\hinet\basicsr\models\__init__.py", line 44, in create_model
    model = model_cls(opt)
  File "c:\users\yusuf\desktop\hmc research\hinet\basicsr\models\image_restoration_model.py", line 37, in __init__
    self.opt['path'].get('strict_load_g', True), param_key=self.opt['path'].get('param_key', 'params'))
  File "c:\users\yusuf\desktop\hmc research\hinet\basicsr\models\base_model.py", line 287, in load_network
    net.load_state_dict(load_net, strict=strict)
  File "C:\Users\Yusuf\anaconda3\envs\HINet\lib\site-packages\torch\nn\modules\module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for HINet:
        Unexpected key(s) in state_dict: "down_path_1.0.norm.weight", "down_path_1.0.norm.bias", "down_path_1.1.norm.weight", "down_path_1.1.norm.bias", "down_path_1.2.norm.weight", "down_path_1.2.norm.bias", "down_path_2.0.norm.weight", "down_path_2.0.norm.bias", "down_path_2.1.norm.weight", "down_path_2.1.norm.bias", "down_path_2.2.norm.weight", "down_path_2.2.norm.bias".
```
